### PR TITLE
Update README, add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Update README, add CONTRIBUTING.md

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Comment by Andersson007** [comment]
ready_for_review

**Review by dericcrago — APPROVED** [review]

**Comment by dericcrago** [comment]
thanks @Andersson007 !

**Comment by Andersson007** [comment]
@dericcrago thanks for reviewing and merging!

**Pull request merged**
