### PR TITLE
[4.0.0] Drop Ansible 2.9 and ansible-base 2.10 compatibility

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Similar to https://github.com/ansible-collections/community.general/pull/4548 and https://github.com/ansible-collections/community.general/pull/4562, officially drop compatibility for Ansible 2.9 and ansible-base 2.10 as announced in the changelog, and replace symlinks with runtime redirects.

##### ISSUE TYPE
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME
collection

### CODE REVIEW

**Comment by felixfontein** [comment]
bot_skip

**Review by Ompragash — APPROVED** [review]
LGTM! Thanks @felixfontein

**Review by Andersson007 — APPROVED** [review]
@felixfontein great job! LGTM

**Comment by felixfontein** [comment]
Follow-up PR in #428, needs this one to pass the (updated) tests.

**Comment by Andersson007** [comment]
@Ompragash would you like to merge this one?:)

**Comment by felixfontein** [comment]
Please don't forget that this needs to be merged and community.network 4.0.0 released by May 23rd :)

**Comment by Ompragash** [comment]
Thanks, Andrei and Felix! I'll merge and close this.

**Comment by felixfontein** [comment]
@Ompragash @Andersson007 thanks for reviewing and merging!

**Pull request merged**
