### PR TITLE
Add icx_aaa_accounting_console.py and test_icx_aaa_accounting_console.py

### PR DESCRIPTION
**Pull request by thamaraig**
##### SUMMARY

- Add icx_aaa_accounting_console.py and test_icx_aaa_accounting_console.py(unit test)

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

- icx_aaa_accounting_console.py
-  test_icx_aaa_accounting_console.py

### CODE REVIEW

**Comment by dericcrago** [comment]
hi @thamaraig - thank you for the PRs in this repo (you've been busy). Do you work for @commscope-ruckus ? Are you aware of ansible collections? We can help you spin these modules out to your own collection that you can maintain in your own GitHub organization / repo.

**Comment by gundalow** [comment]
> The test `ansible-test sanity --test pep8` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/pep8.html)] failed with 1 error:
> 
> ```
> plugins/modules/packaging/language/pear.py:43:161: E501: line too long (164 > 160 characters)
> ```
> 
> [click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

Needs fixing

**Comment by gundalow** [comment]
01:42 ERROR: plugins/modules/network/icx/icx_rate_limit.py:625:0: missing-final-newline: Final newline missing (100%)

```
tests/unit/plugins/modules/network/icx/test_icx_vlan.py::TestICXVlanModule::test_icx_vlan_tagged_cndt 
01:54 
01:54 ==================================== ERRORS ====================================
01:54 ___________________ ERROR collecting test_icx_rate_limit.py ____________________
01:54 ImportError while importing test module '/root/ansible_collections/community/network/tests/unit/plugins/modules/network/icx/test_icx_rate_limit.py'.
01:54 Hint: make sure your test modules/packages have valid Python names.
01:54 Traceback:
01:54 /root/ansible/lib/ansible/utils/collection_loader/_collection_finder.py:360: in load_module
01:54     exec(code_obj, module.__dict__)
01:54 tests/unit/plugins/modules/network/icx/test_icx_rate_limit.py:5: in <module>
01:54     from units.compat.mock import patch
01:54 E   ModuleNotFoundError: No module named 'units'
01:54 - generated xml file: /root/ansible_collections/community/network/tests/output/junit/python3.8-units.xml -
01:54 =========================== short test summary info ============================
01:54 ERROR tests/unit/plugins/modules/network/icx/test_icx_rate_limit.py

```

**Comment by dericcrago** [comment]
closing by request, please let us know if this was in error

**Pull request closed without merging**
