### PR TITLE
ftd httpapi plugin: handle missing urllib3 imports

### LINKED ISSUE #147: ftd httpapi plugin: cannot be loaded without raising an error
##### SUMMARY
The plugin cannot be loaded without raising an error. It should do that when executed, not when being loaded!
```
ERROR: plugins/httpapi/ftd.py:60:0: traceback: ModuleNotFoundError: No module named 'urllib3'
```
See https://github.com/ansible-collections/community.general/blob/ef49950b96849ba8edcd74953a96a16cfd5d653e/plugins/lookup/consul_kv.py#L111-L116 and https://github.com/ansible-collections/community.general/blob/ef49950b96849ba8edcd74953a96a16cfd5d653e/plugins/lookup/consul_kv.py#L123-L125 for how to do this correctly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/httpapi/ftd.py

##### ANSIBLE VERSION
```paste below
latest
```

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fixes #147.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/httpapi/ftd.py

### CODE REVIEW

**Comment by felixfontein** [comment]
recheck

**Review by dmsimard — APPROVED** [review]
This pull request being in the changelog is so meta :+1:

**Comment by felixfontein** [comment]
@dmsimard for most repos it's pretty simple, right before opening the PR, go to https://github.com/ansible-collections/community.network/issues/?q= and look what the latest used number was, and add one. In the unlikely case someone created a PR or issue between you checking the number and creating your own PR, you'll have to force-push or add another commit, but in 99% of the time it'll work fine ;)

**Comment by felixfontein** [comment]
@dmsimard thanks for reviewing and merging!

**Pull request merged**
