### PR TITLE
azure-pipelines: update default test container 1.7.1 -> 1.8.0

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
azure-pipelines: update default test container 1.7.1 -> 1.8.0

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
.azure-pipelines/azure-pipelines.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @felixfontein

**Comment by felixfontein** [comment]
Looks good to me. Deric is maintaining this collection though, so better ask him as well :)

**Comment by Andersson007** [comment]
@felixfontein I didn't know that Deric supports `community.network`:) OK, to wait him sounds good to me :)

**Review by dericcrago — APPROVED** [review]
thanks @Andersson007 !

**Comment by Andersson007** [comment]
@felixfontein @dericcrago thanks for reviewing!

**Pull request merged**
