### PR TITLE
Prepare un-flatmapping

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Prepares un-flatmapping. When collapsing the tests/unit/plugins/modules directory tree, there are some clashes because there are different `fixtures` directories in the tree structure. This PR renames these `fixtures` directories by prepending them with the module group names.

Also removes some string wrapping so that automatic replacements work.

With these changes, https://gist.github.com/felixfontein/3123dcdf446c9e140949a0589cceb99d can remove flatmapping and at least the Python 3.10 unit tests still pass :)

Ref: https://github.com/ansible-community/community-topics/issues/147

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
unit tests

### CODE REVIEW

**Comment by felixfontein** [comment]
Currently contains #470.

**Review by Andersson007 — APPROVED** [review]
Titanic work

**Review by russoz — APPROVED** [review]
LGTM

**Comment by felixfontein** [comment]
@Andersson007 @russoz thanks a lot for reviewing this!

**Pull request merged**
