### PR TITLE
modules: fix examples to use FQCN

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
modules: fix examples to use FQCN

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/overview/issues/45#issuecomment-648405709

**Comment by Andersson007** [comment]
fixed.
ready_for_review

**Comment by Andersson007** [comment]
CC @acozine @samccann

**Comment by felixfontein** [comment]
@Andersson007 thanks a lot for doing this, and @samccann thanks a lot for reviewing this!

**Comment by Andersson007** [comment]
@samccann @felixfontein thanks for reviewing!

**Pull request merged**
