### PR TITLE
Add stable-2.18 to CI, improve CI matrix

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This fixes CI.

##### ISSUE TYPE
- Test Pull Request

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
@felixfontein thanks for the contribution!

**Comment by felixfontein** [comment]
@Andersson007 this PR broke CI.

**Comment by felixfontein** [comment]
I force pushed seconds before you merged, so let's hope it actually passes CI :)

**Comment by Andersson007** [comment]
@felixfontein oh, sorry, didn't noticed it was created 3 minutes ago..

**Comment by felixfontein** [comment]
Better check CI status first, you might have noticed that there was no CI run at all (except the third party check) :)

**Comment by felixfontein** [comment]
I'm offline now, so I won't be able to work on it until this evening.

**Comment by Andersson007** [comment]
> Better check CI status first, you might have noticed that there was no CI run at all (except the third party check) :)

Oh, yes, it's not a good feature about GHA..

> I'm offline now, so I won't be able to work on it until this evening.

No worries, I guess they were broken for a long time anyway. For consistency, I'll merge the backport too

**Pull request merged**
