### PR TITLE
[WIP] nuage_vspk: fix tests

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fix CI

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
tests/integration/targets/prepare_nuage_tests/tasks/main.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
```
ERROR: Test target "nuage_vspk" has changed the test environment!
If these changes are necessary, they must be reverted before the test finishes.
>>> Original Environment
{
    "known_hosts_hash": "41b6a6ee644f2e8359dd15184c9686ec", 
    "pip_interpreters": {
        "": "#!/usr/bin/python", 
        "2": "#!/usr/bin/python"
    }, 
    "pip_paths": {
        "": "/usr/bin/pip", 
        "2": "/usr/bin/pip2", 
        "2.6": null, 
        "2.7": null, 
        "3": null, 
        "3.5": null, 
        "3.6": null, 
        "3.7": null, 
        "3.8": null, 
        "3.9": null
    }, 
    "program_versions": {
        "": [
            "2.7.12 (default, Jul 21 2020, 15:19:50)", 
            "[GCC 5.4.0 20160609]", 
            "pip 8.1.1 from /usr/lib/python2.7/dist-packages/pip"
        ], 
        "2": [
            "2.7.12 (default, Jul 21 2020, 15:19:50)", 
            "[GCC 5.4.0 20160609]", 
            "pip 8.1.1 from /usr/lib/python2.7/dist-packages/pip"
        ], 
        "2.7": [
            "2.7.12 (default, Jul 21 2020, 15:19:50)", 
            "[GCC 5.4.0 20160609]", 
            "pip 8.1.1 from /usr/lib/python2.7/dist-packages/pip"
        ], 
        "3": [
            "3.5.2 (default, Jul 17 2020, 14:04:10)", 
            "[GCC 5.4.0 20160609]"
        ], 
        "3.5": [
            "3.5.2 (default, Jul 17 2020, 14:04:10)", 
            "[GCC 5.4.0 20160609]"
        ]
    }, 
    "python_paths": {
        "": "/usr/bin/python", 
        "2": "/usr/bin/python2", 
        "2.6": null, 
        "2.7": "/usr/bin/python2.7", 
        "3": "/usr/bin/python3", 
        "3.5": "/usr/bin/python3.5", 
        "3.6": null, 
        "3.7": null, 
        "3.8": null, 
        "3.9": null
    }, 
    "warnings": [
        "A Python 2.7 interpreter was found at \"/usr/bin/python2.7\", yet a matching pip was not found.", 
        "A Python 3 interpreter was found at \"/usr/bin/python3\", yet a matching pip was not found.", 
        "A Python 3.5 interpreter was found at \"/usr/bin/python3.5\", yet a matching pip was not found."
    ]
}
>>> Current Environment
{
    "known_hosts_hash": "41b6a6ee644f2e8359dd15184c9686ec", 
    "pip_interpreters": {
        "": "#!/usr/bin/python", 
        "2": "#!/usr/bin/python", 
        "2.7": "#!/usr/bin/python"
    }, 
    "pip_paths": {
        "": "/usr/local/bin/pip", 
        "2": "/usr/local/bin/pip2", 
        "2.6": null, 
        "2.7": "/usr/local/bin/pip2.7", 
        "3": null, 
        "3.5": null, 
        "3.6": null, 
        "3.7": null, 
        "3.8": null, 
        "3.9": null
    }, 
    "program_versions": {
        "": [
            "2.7.12 (default, Jul 21 2020, 15:19:50)", 
            "[GCC 5.4.0 20160609]"
        ], 
        "2": [
            "2.7.12 (default, Jul 21 2020, 15:19:50)", 
            "[GCC 5.4.0 20160609]"
        ], 
        "2.7": [
            "2.7.12 (default, Jul 21 2020, 15:19:50)", 
            "[GCC 5.4.0 20160609]"
        ], 
        "3": [
            "3.5.2 (default, Jul 17 2020, 14:04:10)", 
            "[GCC 5.4.0 20160609]"
        ], 
        "3.5": [
            "3.5.2 (default, Jul 17 2020, 14:04:10)", 
            "[GCC 5.4.0 20160609]"
        ]
    }, 
    "python_paths": {
        "": "/usr/bin/python", 
        "2": "/usr/bin/python2", 
        "2.6": null, 
        "2.7": "/usr/bin/python2.7", 
        "3": "/usr/bin/python3", 
        "3.5": "/usr/bin/python3.5", 
        "3.6": null, 
        "3.7": null, 
        "3.8": null, 
        "3.9": null
    }, 
    "warnings": [
        "A Python 3 interpreter was found at \"/usr/bin/python3\", yet a matching pip was not found.", 
        "A Python 3.5 interpreter was found at \"/usr/bin/python3.5\", yet a matching pip was not found."
    ]
}
>>> Environment Diff
--- original.json
+++ current.json
@@ -2,13 +2,14 @@
     "known_hosts_hash": "41b6a6ee644f2e8359dd15184c9686ec", 
     "pip_interpreters": {
         "": "#!/usr/bin/python", 
-        "2": "#!/usr/bin/python"
+        "2": "#!/usr/bin/python", 
+        "2.7": "#!/usr/bin/python"
     }, 
     "pip_paths": {
-        "": "/usr/bin/pip", 
-        "2": "/usr/bin/pip2", 
+        "": "/usr/local/bin/pip", 
+        "2": "/usr/local/bin/pip2", 
         "2.6": null, 
-        "2.7": null, 
+        "2.7": "/usr/local/bin/pip2.7", 
         "3": null, 
         "3.5": null, 
         "3.6": null, 
@@ -19,18 +20,15 @@
     "program_versions": {
         "": [
             "2.7.12 (default, Jul 21 2020, 15:19:50)", 
-            "[GCC 5.4.0 20160609]", 
-            "pip 8.1.1 from /usr/lib/python2.7/dist-packages/pip"
+            "[GCC 5.4.0 20160609]"
         ], 
         "2": [
             "2.7.12 (default, Jul 21 2020, 15:19:50)", 
-            "[GCC 5.4.0 20160609]", 
-            "pip 8.1.1 from /usr/lib/python2.7/dist-packages/pip"
+            "[GCC 5.4.0 20160609]"
         ], 
         "2.7": [
             "2.7.12 (default, Jul 21 2020, 15:19:50)", 
-            "[GCC 5.4.0 20160609]", 
-            "pip 8.1.1 from /usr/lib/python2.7/dist-packages/pip"
+            "[GCC 5.4.0 20160609]"
         ], 
         "3": [
             "3.5.2 (default, Jul 17 2020, 14:04:10)", 
@@ -54,7 +52,6 @@
         "3.9": null
     }, 
     "warnings": [
-        "A Python 2.7 interpreter was found at \"/usr/bin/python2.7\", yet a matching pip was not found.", 
         "A Python 3 interpreter was found at \"/usr/bin/python3\", yet a matching pip was not found.", 
         "A Python 3.5 interpreter was found at \"/usr/bin/python3.5\", yet a matching pip was not found."
     ]
NOTICE: To resume at this test target, use the option: --start-at nuage_vspk
ERROR: Command "ansible-playbook nuage_vspk-2I_kwW.yml -i inventory -vvv" returned exit status 2.
ERROR: Command "docker exec f29c30232527351af8a294a922c9ad5643f80ca8a7379d14fd975c8848f2eff5 /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/community/network LC_ALL=en_US.UTF-8 /usr/bin/python2.7 /root/ansible/bin/ansible-test integration nuage_vspk --python 2.7 -vvv --metadata tests/output/.tmp/metadata-sv1qhzow.json --truncate 92 --redact --color no --requirements --allow-destructive" returned exit status 1.
```

**Comment by Andersson007** [comment]
```
    "msg": "stdout: Collecting setuptools\n  Downloading https://files.pythonhosted.org/packages/fc/0a/b486efab52f8ad03c3eca0c998dd3deafba0c39b29e0c49c68a7152c8b2d/setuptools-56.2.0.tar.gz (2.1MB)\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"setuptools/__init__.py\", line 16, in <module>\n        import setuptools.version\n      File \"setuptools/version.py\", line 1, in <module>\n        import pkg_resources\n      File \"pkg_resources/__init__.py\", line 1367\n        raise SyntaxError(e) from e\n                                ^\n    SyntaxError: invalid syntax\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-6E_IfB/setuptools/\nYou are using pip version 8.1.2, however version 21.1.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"
}
```

**Comment by Andersson007** [comment]
@dericcrago people say that updating setuptools fixes the issue.
https://github.com/click-contrib/click-completion/issues/29
https://github.com/sdispater/pendulum/issues/187
https://github.com/ansible-community/molecule/issues/1859
I failed to update it on the old distros, see the error above.

As we discussed with @felixfontein, now the tests are very redundant in terms of the number of distros involved. We could:
1) remove CentOS 7 and Ubuntu 1604 from the test matrix
2) or use the default container

**Comment by felixfontein** [comment]
For network modules, just testing with the `default` container is probably best.

**Pull request closed without merging**
