### PR TITLE
removed for Ansible 2.9

### PR DESCRIPTION
**Pull request by xuxiaowei0512**
##### SUMMARY

See ansible/ansible#67020 and ansible-collections/community.network#61

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

```
lib/ansible/modules/network/cloudengine/ce_aaa_server.py
lib/ansible/modules/network/cloudengine/ce_aaa_server_host.py
lib/ansible/modules/network/cloudengine/ce_acl.py
lib/ansible/modules/network/cloudengine/ce_acl_advance.py
lib/ansible/modules/network/cloudengine/ce_acl_interface.py
lib/ansible/modules/network/cloudengine/ce_bfd_global.py
lib/ansible/modules/network/cloudengine/ce_bfd_session.py
lib/ansible/modules/network/cloudengine/ce_bfd_view.py
lib/ansible/modules/network/cloudengine/ce_bgp.py
lib/ansible/modules/network/cloudengine/ce_bgp_af.py
lib/ansible/modules/network/cloudengine/ce_bgp_neighbor.py
lib/ansible/modules/network/cloudengine/ce_bgp_neighbor_af.py
lib/ansible/modules/network/cloudengine/ce_command.py
lib/ansible/modules/network/cloudengine/ce_config.py
lib/ansible/modules/network/cloudengine/ce_dldp.py
lib/ansible/modules/network/cloudengine/ce_dldp_interface.py
lib/ansible/modules/network/cloudengine/ce_eth_trunk.py
lib/ansible/modules/network/cloudengine/ce_evpn_bd_vni.py
lib/ansible/modules/network/cloudengine/ce_evpn_bgp.py
lib/ansible/modules/network/cloudengine/ce_evpn_bgp_rr.py
lib/ansible/modules/network/cloudengine/ce_evpn_global.py
lib/ansible/modules/network/cloudengine/ce_facts.py
lib/ansible/modules/network/cloudengine/ce_file_copy.py
lib/ansible/modules/network/cloudengine/ce_info_center_debug.py
lib/ansible/modules/network/cloudengine/ce_info_center_global.py
lib/ansible/modules/network/cloudengine/ce_info_center_log.py
lib/ansible/modules/network/cloudengine/ce_info_center_trap.py
lib/ansible/modules/network/cloudengine/ce_interface.py
lib/ansible/modules/network/cloudengine/ce_interface_ospf.py
lib/ansible/modules/network/cloudengine/ce_ip_interface.py
lib/ansible/modules/network/cloudengine/ce_link_status.py
lib/ansible/modules/network/cloudengine/ce_mlag_config.py
lib/ansible/modules/network/cloudengine/ce_mlag_interface.py
lib/ansible/modules/network/cloudengine/ce_mtu.py
lib/ansible/modules/network/cloudengine/ce_netconf.py
lib/ansible/modules/network/cloudengine/ce_netstream_aging.py
lib/ansible/modules/network/cloudengine/ce_netstream_export.py
lib/ansible/modules/network/cloudengine/ce_netstream_global.py
lib/ansible/modules/network/cloudengine/ce_netstream_template.py
lib/ansible/modules/network/cloudengine/ce_ntp.py
lib/ansible/modules/network/cloudengine/ce_ntp_auth.py
lib/ansible/modules/network/cloudengine/ce_ospf.py
lib/ansible/modules/network/cloudengine/ce_ospf_vrf.py
lib/ansible/modules/network/cloudengine/ce_reboot.py
lib/ansible/modules/network/cloudengine/ce_rollback.py
lib/ansible/modules/network/cloudengine/ce_sflow.py
lib/ansible/modules/network/cloudengine/ce_snmp_community.py
lib/ansible/modules/network/cloudengine/ce_snmp_contact.py
lib/ansible/modules/network/cloudengine/ce_snmp_location.py
lib/ansible/modules/network/cloudengine/ce_snmp_target_host.py
lib/ansible/modules/network/cloudengine/ce_snmp_traps.py
lib/ansible/modules/network/cloudengine/ce_startup.py
lib/ansible/modules/network/cloudengine/ce_static_route.py
lib/ansible/modules/network/cloudengine/ce_stp.py
lib/ansible/modules/network/cloudengine/ce_switchport.py
lib/ansible/modules/network/cloudengine/ce_vlan.py
lib/ansible/modules/network/cloudengine/ce_vrf.py
lib/ansible/modules/network/cloudengine/ce_vrf_af.py
lib/ansible/modules/network/cloudengine/ce_vrf_interface.py
lib/ansible/modules/network/cloudengine/ce_vrrp.py
lib/ansible/modules/network/cloudengine/ce_vxlan_arp.py
lib/ansible/modules/network/cloudengine/ce_vxlan_gateway.py
lib/ansible/modules/network/cloudengine/ce_vxlan_global.py
lib/ansible/modules/network/cloudengine/ce_vxlan_tunnel.py
lib/ansible/modules/network/cloudengine/ce_vxlan_vap.py
```
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by felixfontein** [comment]
@xuxiaowei0512 can you add a changelog fragment with `removed_features` section?

**Comment by xuxiaowei0512** [comment]
> @xuxiaowei0512 can you add a changelog fragment with `removed_features` section?
@felixfontein 
Hi, guy, It is a long time to see you again.Are you ok?
Of course, changlog fragment.

**Comment by felixfontein** [comment]
> Hi, guy, It is a long time to see you again.Are you ok?

Yes, busy as usual, but I'm fine! How about you?

**Comment by felixfontein** [comment]
Oh crap, I noticed only after merging that this PR removed too much. It also removed deprecations that were only supposed to be removed in Ansible 2.13. These have to stay. I'll revert these.

**Comment by felixfontein** [comment]
Fixed it in #69.

**Comment by xuxiaowei0512** [comment]
> > Hi, guy, It is a long time to see you again.Are you ok?
> 
> Yes, busy as usual, but I'm fine! How about you?

Everything is ok ,but time go fast ^-^

**Comment by xuxiaowei0512** [comment]
> Oh crap, I noticed only after merging that this PR removed too much. It also removed deprecations that were only supposed to be removed in Ansible 2.13. These have to stay. I'll revert these.

Sorry for a mistake, sleepy always shake my head yesterday.

**Comment by felixfontein** [comment]
@xuxiaowei0512 no problem, I wasn't doing much better either by not spotting it ;)

**Pull request merged**
