### PR TITLE
[stable-1] community.fortios removal announcement

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Can be merged once #50 has been merged.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
changelog

### CODE REVIEW

**Comment by felixfontein** [comment]
CC @dericcrago

**Review by dericcrago — APPROVED** [review]

**Comment by dericcrago** [comment]
thanks @felixfontein !

**Comment by felixfontein** [comment]
Shippable has finished successfully (https://app.shippable.com/github/ansible-collections/community.network/runs/926/summary/console), it looks like this status hasn't been propagated to GitHub yet. Merging anyway.

**Comment by felixfontein** [comment]
@dericcrago thanks for reviewing!

**Pull request merged**
