### PR TITLE
[stable-3] Fix (most of) CI

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Try to fix CI for stable-3 branch.

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by felixfontein** [comment]
@Andersson007 this doesn't fix everything (the 3.8 unit tests still fail with stable-2.14), but it fixes most of the issues.

**Review by Andersson007 — APPROVED** [review]
@felixfontein LGTM, thanks!

**Comment by Andersson007** [comment]
@felixfontein should we backport it to stable-2?

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing and merging!

Aren't stable-1 and stable-2 EOL?

**Comment by Andersson007** [comment]
I don't see any info about how many past versions the collection supports. I thought it's two besides the latest. If you agreed to support only one past version, I'd be happy with it. Do you have any info on this?

**Comment by felixfontein** [comment]
The changelogs say so:
- https://github.com/ansible-collections/community.network/blob/stable-1/CHANGELOG.rst#major-changes
- https://github.com/ansible-collections/community.network/blob/stable-2/CHANGELOG.rst#major-changes

Besides that I couldn't find any hint. stable-2 even still has weekly CI (https://github.com/ansible-collections/community.network/blob/main/.azure-pipelines/azure-pipelines.yml#L34, though maybe this is controlled by that file in stable-1/stable-2 instead, in which case even stable-1 still has regular CI runs).

**Comment by Andersson007** [comment]
@felixfontein thanks for the info!
I'll remove CI runs against all of the old branches

**Pull request merged**
