### PR TITLE
Removing bigmstone

### PR DESCRIPTION
**Pull request by bigmstone**
##### SUMMARY
Removing references to bigmstone in BOTMETA.

##### ISSUE TYPE
- N/A

### CODE REVIEW

**Comment by bigmstone** [comment]
I am unsure if I should also remove myself as `author` or if the changes I've made is sufficient to remove notifications.

**Comment by felixfontein** [comment]
@bigmstone for modules/plugins where you are listed in the `author` list, you should not modify that list, but instead use `ignore:` in BOTMETA to make the bot no longer ping you. That way your authorship is preserved (and still visible), but you won't get pinged anymore. For an example, see here https://github.com/ansible-collections/community.network/blob/8dbfd75f1618a115592124479b3a880e089d368f/.github/BOTMETA.yml#L137.

**Comment by bigmstone** [comment]
@felixfontein thanks. I have updated accordingly.

**Review by felixfontein — APPROVED** [review]

**Comment by felixfontein** [comment]
@bigmstone also for this collection, thanks a lot for being maintainer, and for authoring some of the modules! If you ever want to maintain something again here, feel free to create a PR which reverts this one! :)

**Pull request merged**
