### PR TITLE
Unflatmap community.network

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See https://github.com/ansible-community/community-topics/issues/147. At today's community meeting we (who were present) informally agreed to make community.general and community.network flat (however you want to call it).

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
collection

### CODE REVIEW

**Comment by felixfontein** [comment]
bot_skip

**Comment by felixfontein** [comment]
@Ompragash @Andersson007 it's basically up to you how you want to proceed with this. For community.general, I will merge the corresponding PR (https://github.com/ansible-collections/community.general/pull/5461) as soon as CI passes (and there are no comments) and release a 6.0.0a1 version with it, and if there's no bad surprise the plan is to include it in next Monday's community.general 6.0.0 release.

**Comment by felixfontein** [comment]
Note that merging this will introduce conflicts to probably all other PRs. If you merge this, here are some messages you can write into these PRs (I added similar messages depending on the situation to all community.general PRs that modified/added modules):

> Please note that in #482 the collection repository was restructured to remove the directory tree in plugins/modules/, and the corresponding tree in tests/unit/plugins/modules/. Your PR modifies files in this directory structure, but it seems that GitHub can still manage the renames. If you suddenly notice that there are strange conflicts, these could come from that change and rebasing with the current `main` branch should fix them.

> Please note that in #482 the collection repository was restructured to remove the directory tree in plugins/modules/, and the corresponding tree in tests/unit/plugins/modules/. Your PR modifies files in this directory structure, and unfortunately now has some conflicts, potentially because of this. Please **rebase** with the current `main` branch to remove the conflicts.

> Please note that in #482 the collection repository was restructured to remove the directory tree in plugins/modules/, and the corresponding tree in tests/unit/plugins/modules/. Your PR adds new files into this hierarchy. Please **rebase** with the current `main` branch and move your files directly into plugins/modules/. You also can remove the changes to meta/runtime.yml, these are not needed anymore, and make sure to adjust the new entries in .github/BOTMETA.yml as well.

**Comment by Andersson007** [comment]
@felixfontein thanks for working on this!

So what should we do to be in time:
- Merge https://github.com/ansible-collections/community.network/pull/482 now
- release version 5, put 5.0.0 tag today
- create branch stable-5 from that commit?

**Review by Andersson007 — APPROVED** [review]

**Comment by felixfontein** [comment]
@Andersson007 thanks!

**Pull request merged**
