### PR TITLE
fixed: variable 'rsp' referenced before assignment

### PR DESCRIPTION
**Pull request by rothman857**
##### SUMMARY

The following task is not idempotent:
```- name: Set Admin Password
    community.network.avi_useraccount:
      avi_credentials: "{{ avi_credentials }}"
      old_password: "{{ avi_default_password }}"
      force_change: True
      password: "{{ avi_password }}"
      username: "{{ avi_username }}"
```

On the first run it completes successfully, but subsequent runs result in the following error:
```
line 148, in main\nUnboundLocalError: local variable 'rsp' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

community.network.avi_useraccount

##### ADDITIONAL INFORMATION

Run this task more than once in succession:
```- name: Set Admin Password
    community.network.avi_useraccount:
      avi_credentials: "{{ avi_credentials }}"
      old_password: "{{ avi_default_password }}"
      force_change: True
      password: "{{ avi_password }}"
      username: "{{ avi_username }}"
```

After a successful first run, subsequent runs will fail.

Before:
```
TASK [Set Admin Password] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/home/vagrant/.venv/lib64/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.xxx.xxx.xxx'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nStatus Code 401 msg {\"error\": \"Invalid credentials\"}\n/home/vagrant/.venv/lib64/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.xxx.xxx.xxx'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning,\nTraceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1613701146.246441-11203-84759223293469/AnsiballZ_avi_useraccount.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1613701146.246441-11203-84759223293469/AnsiballZ_avi_useraccount.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1613701146.246441-11203-84759223293469/AnsiballZ_avi_useraccount.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.network.plugins.modules.avi_useraccount', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.network.avi_useraccount_payload_tjd3xypl/ansible_community.network.avi_useraccount_payload.zip/ansible_collections/community/network/plugins/modules/avi_useraccount.py\", line 152, in <module>\n  File \"/tmp/ansible_community.network.avi_useraccount_payload_tjd3xypl/ansible_community.network.avi_useraccount_payload.zip/ansible_collections/community/network/plugins/modules/avi_useraccount.py\", line 148, in main\nUnboundLocalError: local variable 'rsp' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

After:
```
TASK [Set Admin Password] ******************************************************************************************************************
ok: [localhost]
```

### CODE REVIEW

**Comment by dericcrago** [comment]
Hi @chaitanyaavi @ericsysmin @grastogi23 @khaltore, this looks like a 1 line fix for `avi_useraccount`, is this ok to merge?

**Comment by chaitanyaavi** [comment]
+@Sandeep ***@***.***>

From: Deric Crago ***@***.***>
Reply to: "ansible-collections/community.network" ***@***.***>
Date: Tuesday, 6 April 2021 at 8:54 PM
To: "ansible-collections/community.network" ***@***.***>
Cc: Chaitanya Deshpande ***@***.***>, Mention ***@***.***>
Subject: Re: [ansible-collections/community.network] fixed: variable 'rsp' referenced before assignment (#218)


Hi @chaitanyaavi<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchaitanyaavi&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461528438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rUItjH%2Btaf8l6m34FBgJ7RA07ECxwfRWggFTXftpCNs%3D&reserved=0> @ericsysmin<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fericsysmin&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461528438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dTF7%2BTVkyqDAl3Jemngd1syygOVCYVehII5moYOIt0w%3D&reserved=0> @grastogi23<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrastogi23&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461538439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OT9sNZtyc5NVUlbdb8jFzpm2w6XkWqdxaf1kipLzbbM%3D&reserved=0> @khaltore<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkhaltore&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461538439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e6AgGnT1RFkUXJ3ZeKLmOBfGkuSkYVTGEtdCUekrMP0%3D&reserved=0>, this looks like a 1 line fix for avi_useraccount, is this ok to merge?

**Comment by chaitanyaavi** [comment]
@Amol Shinde ***@***.***> can you please validate the fix and update the thread.

Thanks,
Sandeep
From: Chaitanya Deshpande ***@***.***>
Date: Tuesday, 6 April 2021 at 8:59 PM
To: "ansible-collections/community.network" ***@***.***>, "ansible-collections/community.network" ***@***.***>, Sandeep Bandi ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [ansible-collections/community.network] fixed: variable 'rsp' referenced before assignment (#218)

+@Sandeep ***@***.***>

From: Deric Crago ***@***.***>
Reply to: "ansible-collections/community.network" ***@***.***>
Date: Tuesday, 6 April 2021 at 8:54 PM
To: "ansible-collections/community.network" ***@***.***>
Cc: Chaitanya Deshpande ***@***.***>, Mention ***@***.***>
Subject: Re: [ansible-collections/community.network] fixed: variable 'rsp' referenced before assignment (#218)


Hi @chaitanyaavi<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchaitanyaavi&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461528438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rUItjH%2Btaf8l6m34FBgJ7RA07ECxwfRWggFTXftpCNs%3D&reserved=0> @ericsysmin<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fericsysmin&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461528438%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dTF7%2BTVkyqDAl3Jemngd1syygOVCYVehII5moYOIt0w%3D&reserved=0> @grastogi23<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgrastogi23&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461538439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OT9sNZtyc5NVUlbdb8jFzpm2w6XkWqdxaf1kipLzbbM%3D&reserved=0> @khaltore<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkhaltore&data=04%7C01%7Cdeshpandech%40vmware.com%7Cc29d9f2ee3c94e89382a08d8f9100377%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637533194461538439%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e6AgGnT1RFkUXJ3ZeKLmOBfGkuSkYVTGEtdCUekrMP0%3D&reserved=0>, this looks like a 1 line fix for avi_useraccount, is this ok to merge?

**Comment by rothman857** [comment]
I noticed the fix was included in the new vmware.alb collection.  I think this can be closed out.

**Comment by dericcrago** [comment]
thank you for your contribution @rothman857

**Pull request merged**
