### PR TITLE
Adding labels to the tags section

### PR DESCRIPTION
**Pull request by JPrause**
Fixes https://github.com/ansible-collections/community.network/issues/23

### CODE REVIEW

**Comment by gundalow** [comment]
@JPrause Thanks for adding these. FYI no need to raise an issue first. 
We use GitHub Issues to make a note that someone needs to do something, or discussion *before* implementation.

**Comment by JPrause** [comment]
Thanks @gundalow and appreciate the suggestion about opening issues. Will remember going forward.

**Comment by JPrause** [comment]
Question @gundalow 
Does a bot merge this, or do you.
Trying to understand process.

**Comment by felixfontein** [comment]
@JPrause merging is done manually; I haven't merged this yet since I don't know if there's a procedure / some requirements for tags I don't know about. @gundalow can you take a look?

**Comment by JPrause** [comment]
Thanks for both of your help!

**Comment by JPrause** [comment]
APM-4 #close

**Comment by JPrause** [comment]
close

**Pull request merged**
