### PR TITLE
Remove ANSIBLE_METADATA

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Remove ANSIBLE_METADATA

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
CC @gundalow @felixfontein  @resmo

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/overview/issues/57

**Comment by felixfontein** [comment]
If we ever need this, the following modules had `supported_by: network`:
```
network/check_point/checkpoint_host.py
network/check_point/checkpoint_access_rule.py
network/check_point/checkpoint_run_script.py
network/check_point/checkpoint_host_facts.py
network/check_point/checkpoint_task_facts.py
network/check_point/checkpoint_access_rule_facts.py
network/check_point/checkpoint_object_facts.py
network/check_point/checkpoint_session.py
network/check_point/checkpoint_access_layer_facts.py
```

**Comment by Andersson007** [comment]
@felixfontein  thanks for reviewing!

**Comment by felixfontein** [comment]
@Andersson007 thanks for doing all the work!

**Comment by Andersson007** [comment]
@felixfontein thanks for reviewing and merging!

**Pull request merged**
