### PR TITLE
Add "Permission denied" error handling for Extreme Exos

### PR DESCRIPTION
**Pull request by Thorbijoern**
##### SUMMARY

I stumbled over an error with the scp2 command on a 5320 model switch with EXOS Version 31.x

`Couldn't open local file \"/scratch/summit_arm-32.4.1.10.xos\" for writing: Permission denied`

Ansible/the exos modules don't recognize it as error and pretend it's fine. So i just want to add it in case somebody else has a similar problem and it might help.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

exos

##### ADDITIONAL INFORMATION

It only happens on a switch that is freshly unconfigured. It's probably a bug, but i use download image for now. I don't know the exact Exos version anymore, i would have to downgrade the switch and test a bit.

```paste below

```

### CODE REVIEW

**Comment by Andersson007** [comment]
@Thorbijoern hello, thanks for the fix!
Could you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment)?

**Comment by Andersson007** [comment]
@Thorbijoern ^ ?

**Comment by Thorbijoern** [comment]
Sorry for forgetting to follow up with this PR. I added the changelog fragment.

**Comment by Andersson007** [comment]
@Thorbijoern that's OK, thanks for adding the fragment and for the bugfix!
Just a fyi, this is the only merged PR since the previous release, so I wouldn't expect the fix to be available in the package soon: I would wait for a bit more fixes/new features to release them at once.

**Pull request merged**
