### PR TITLE
cumulus/nclu: support diff mode

### LINKED ISSUE #250: NCLU support diff
##### SUMMARY

the cumulus NCLU module should support diff mode.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nclu

##### ADDITIONAL INFORMATION

diff mode is suggested by the how-to-module guide.

### PR DESCRIPTION
**Pull request by MEschenbacher**
##### SUMMARY

This pull request attempts to address issue #250  (Fixes #250).

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

cumulus/nclu

##### ADDITIONAL INFORMATION

implements diff mode

### CODE REVIEW

**Comment by dericcrago** [comment]
Hi @MEschenbacher, thank you for this PR! Can you add a changelog fragment (https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to) please?

**Comment by MEschenbacher** [comment]
I've added a fragment to `changelogs/fragments`.

**Comment by dericcrago** [comment]
@MEschenbacher - thank you for the changelog! I was just thinking, does the `DOCUMENTATION` block also need updated? Specifically, the `RETURN` block came to mind, but maybe elsewhere as well. 🤷 Thanks!

**Comment by dericcrago** [comment]
cc @isharacomix @jrrivers - are you able to review?

**Comment by dericcrago** [comment]
hi @MEschenbacher, thank you for this contribution. I believe this functionality has been added by the recently merged https://github.com/ansible-collections/community.network/pull/103. Please take a look and if you agree, close this PR, if not, let's discuss. Thanks!

**Comment by MEschenbacher** [comment]
Looks good to me!

**Pull request closed without merging**
