### PR TITLE
Fix non-matching defaults in docs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Fix various non-matching `default` values exposed by https://github.com/ansible/ansible/pull/79267.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
various

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
@felixfontein LGTM thanks!

**Review by maxamillion — APPROVED** [review]

**Comment by maxamillion** [comment]
shipit

**Comment by felixfontein** [comment]
Merging to avoid sanity test failures in `main`.

**Comment by felixfontein** [comment]
@Andersson007 @maxamillion thanks for reviewing this!

**Pull request merged**
