### PR TITLE
[4.0.0] Add sanity check for non-regular files in plugins/

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Follow-up to #426, will fail until that one is merged. It will report all symlinks or other non-regular files in plugins/.

I also included support for `.yml` files in plugins/test/ and plugins/filter/ for the upcoming sidecar docs feature of ansible-core 2.14 (https://github.com/ansible/ansible/pull/74963). Not sure whether this is really needed, but if someone ever wants to add test and filter plugins to this collection, it will save them some pain :)

##### ISSUE TYPE
- Test Pull Request

##### COMPONENT NAME
CI

### CODE REVIEW

**Comment by bcoca** [comment]
fyi, the.yml files are not permitted to document any of the 'documentable' plugins, but most likely the use will be for 'non python modules'  to use .yml instead of a .py doc stub.

**Comment by felixfontein** [comment]
Restarting tests.

**Comment by Ompragash** [comment]
Thanks for the PR @felixfontein!

**Comment by felixfontein** [comment]
@bcoca @Ompragash thanks for reviewing and merging!

**Pull request merged**
