### PR TITLE
Clean up deprecations

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
This adjusts the deprecation versions as decided in the community working group meeting (https://meetbot.fedoraproject.org/ansible-community/2020-06-10/community_working_group.2020-06-10-18.04.html), and adjusts the ignore.txt entries.

It also removes some F5 modules which according to https://github.com/ansible/ansible/blob/devel/lib/ansible/config/ansible_builtin_runtime.yml have been moved to the F5 collection.

Then it adjusts the deprecations which were scheduled for removal in Ansible 2.9 for removal in 0.2.0 (next released version), and adds ignore.txt entries for these.

Finally, it comments out the aci_intf_policy_port_* deprecation entries in meta/runtime.yml sind according to the modules themselves, they are not deprecated. @gundalow do you know where the deprecation entries come from?

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
collection

### CODE REVIEW

**Comment by felixfontein** [comment]
I used https://gist.github.com/felixfontein/964068eed7e8d233f77abe097eef31a7 to clean up meta/runtime.yml and remove some modules that have apparently been moved somewhere else meanwhile.

**Comment by felixfontein** [comment]
@gundalow these aci_intf_policy_port_* modules are redirects to the aci_interface_policy_* modules, which have been moved to cisco.aci. I've removed the traces; I'll create a PR to update ansible/ansible's ansible_builtin_runtime.yml.

**Comment by felixfontein** [comment]
(See ansible/ansible#70051)

**Comment by felixfontein** [comment]
CC @Andersson007

**Comment by felixfontein** [comment]
@gundalow @Andersson007 thanks a lot for reviewing this! :)

**Comment by Andersson007** [comment]
Yw,
just in case, if i were you, i'd also run `grep -r "Ansible 2.10" plugins/ | grep -v " # was "` with  2.11, 2.12, 2.13, 2.14 as i did in https://github.com/ansible-collections/community.general/pull/504

**Comment by Andersson007** [comment]
`grep -r "Ansible 2.1[0-4]" ...`

**Comment by felixfontein** [comment]
@Andersson007 found nothing in this repo.

**Comment by Andersson007** [comment]
@felixfontein cool

**Pull request merged**
