### PR TITLE
New module: cumulus linux nvue

### LINKED ISSUE #319: Cumulus Linux: support for new nvue syntax
##### SUMMARY

Cumulus Linux now supports a new command line syntax [nvue](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-44/System-Configuration/NVIDIA-User-Experience-NVUE/#list-all-nvue-commands). Currently, there are some configurations which can not be done with nclu but only with nvue and vice versa.

Example for nclu lacking configuration options which nvue provides: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-44/Network-Virtualization/VXLAN-Devices/#single-vxlan-device

Example for nvue lacking configuration options which nclu provides: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-43/Layer-3/VRFs/Virtual-Routing-and-Forwarding-VRF/

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I propose either
  - option 1) a new module similar to `community.network.nclu` called `community.network.nvue`
  - option 2) a compatibility mode to `community.network.nclu` which can then be used to issue not only nclu commands but also nvue commands

##### ADDITIONAL INFORMATION

I am leaning towards option 2 because neither nclu nor nvue are currently *completely* covering all possible configuration options and therefore one *single* module should be able to provide an interface all configuration options.

Example for option 2) (note the *new* parameter `cli` which should default to `nvue` but may be set to `nvue`.

```yml
- name: configure vrf
  community.network.nclu:
    cli: nvue
    template: |
      {% for name in ['internal', 'external'] %}
        add vrf {{name}} vrf-table auto
      {% endfor %}
```

### PR DESCRIPTION
**Pull request by MEschenbacher**
##### SUMMARY

Starting with cumulus 5.0, `nclu` cannot be used to configure cumulus linux.

Fixes #319

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

`ansible.community.nvue`

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by MEschenbacher** [comment]
We've been using the module for more than one year. I've rebased my commit onto the current master.

**Comment by MEschenbacher** [comment]
Hey,

> @MEschenbacher hi, thanks for continuing to work on the module!
> 
>     * I think you need to move the module directly to `/plugins/modules`

okay, done :)

>     * please add unit tests if possible (if not, try to rearrange the code to make it possible maybe not for all but at least for some functions)

Sure, I'll look into it.

>     * is it possible that in future there will be more modules for automating the underlying stuff? I'm thinking maybe it makes sense to create a separate collection right now? i'd like to avoid situations when in future we need to move this to another collection.

As far as I can tell, nvue is supposed to be the interface that is able to fully configure Cumulus Linux (modulo some system configuration files). The switch from nclu to nvue was probably a one time operation and there should be (hopefully) no need for vastly extending the module into a bigger system.

**Comment by Andersson007** [comment]
@MEschenbacher thanks for the feedback!
Could you also please fix sanity tests? If you click the red crosses in the test box at the bottom you'll see something like:
```
01:16 ERROR: Found 6 pep8 issue(s) which need to be resolved:
01:16 ERROR: plugins/modules/nvue.py:110:1: E302: expected 2 blank lines, found 1 (100%)
01:16 ERROR: plugins/modules/nvue.py:120:1: E302: expected 2 blank lines, found 1 (100%)
01:16 ERROR: plugins/modules/nvue.py:123:1: E302: expected 2 blank lines, found 1 (100%)
01:16 ERROR: plugins/modules/nvue.py:162:1: E302: expected 2 blank lines, found 1 (100%)
01:16 ERROR: plugins/modules/nvue.py:175:9: E123: closing bracket does not match indentation of opening bracket's line (100%)
01:16 ERROR: plugins/modules/nvue.py:182:1: E305: expected 2 blank lines after class or function definition, found 1 (100%)
01:16 See documentation for help: https://docs.ansible.com/ansible-core/devel/dev_guide/testing/sanity/pep8.html
```

**Comment by pescobar** [comment]
Are there any plans to get this module merged?

**Comment by Andersson007** [comment]
@pescobar thanks for the info! I'll close the PR then
@MEschenbacher thanks

**Pull request closed without merging**
