### PR TITLE
[stable-1] Add Cisco NSO removal announcement

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
See ansible-collections/overview#128.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
changelog

### CODE REVIEW

**Comment by felixfontein** [comment]
recheck

**Comment by felixfontein** [comment]
recheck

**Review by Andersson007 — APPROVED** [review]
LGTM and the same about the abbreviation

**Review by gundalow — APPROVED** [review]

**Comment by felixfontein** [comment]
@Andersson007 @gundalow thanks for reviewing!

**Pull request merged**
